### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by thetruechar** [johnpapa/angular2-tour-of-heroes#47]
> angular2-tour-of-heroes@0.0.1 lite F:\dev\angular2\angular2-tour-of-heroes
> lite-server

[BS] Access URLs:

---

```
   Local: http://localhost:3001
External: http://192.168.31.133:3001
```

---

```
      UI: http://localhost:3002
```

 UI External: http://192.168.31.133:3002

---

[BS] Serving files from: ./
[BS] Watching files...
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
    at onErrorNT (internal/child_process.js:345:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "lite"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.0.1 lite: `lite-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-tour-of-heroes@0.0.1 lite script 'lite-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lite-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\dev\angular2\angular2-tour-of-heroes\npm-debug.log

Process finished with exit code 1

**Comment by johnpapa** [comment]
thanks for reporting this. i just re cloned and tried this and it worked. can you provide your version of node and npm and any other environmental specifics?

**Comment by thetruechar** [comment]
windows 10
[npm-debug.zip](https://github.com/johnpapa/angular2-tour-of-heroes/files/88273/npm-debug.zip)

$ node -v
v5.2.0
$ npm -v
3.3.12

**Comment by DirectX** [comment]
Similar problem on Linux installation

user@pc:~/projects/samples/angular2-tour-of-heroes-master$ uname -a
Linux pc 3.16.0-44-generic #59~14.04.1-Ubuntu SMP Tue Jul 7 15:07:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

user@pc:~/projects/samples/angular2-tour-of-heroes-master$ node -v
v5.4.1

user@pc:~/projects/samples/angular2-tour-of-heroes-master$ npm -v
3.3.12

user@pc:~/projects/samples/angular2-tour-of-heroes-master$ npm start

> angular2-tour-of-heroes@0.0.1 start /home/user/projects/samples/angular2-tour-of-heroes-master
> concurrent "npm run tsc:w" "npm run lite" 

[0] 
[0] > angular2-tour-of-heroes@0.0.1 tsc:w /home/user/projects/samples/angular2-tour-of-heroes-master
[0] > tsc -w
[0] 
[1] 
[1] > angular2-tour-of-heroes@0.0.1 lite /home/user/projects/samples/angular2-tour-of-heroes-master
[1] > lite-server
[1] 
[1] [BS] Access URLs:
[1]  --------------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://192.168.1.116:3000
[1]  --------------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://192.168.1.116:3001
[1]  --------------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] events.js:141
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: watch node_modules/graceful-fs ENOSPC
[1]     at exports._errnoException (util.js:856:11)
[1]     at FSWatcher.start (fs.js:1313:19)
[1]     at Object.fs.watch (fs.js:1341:11)
[1]     at createFsWatchInstance (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[1]     at setFsWatchListener (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[1]     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[1]     at FSWatcher.NodeFsHandler._handleDir (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:407:19)
[1]     at FSWatcher.<anonymous> (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:455:19)
[1]     at FSWatcher.<anonymous> (/home/user/projects/samples/angular2-tour-of-heroes-master/node_modules/chokidar/lib/nodefs-handler.js:460:16)
[1]     at FSReqWrap.oncomplete (fs.js:82:15)
[1] 
[1] npm 
[1] ERR! Linux 3.16.0-44-generic
[1] npm ERR! argv "/home/user/.nvm/versions/node/v5.4.1/bin/node" "/home/user/.nvm/versions/node/v5.4.1/bin/npm" "run" "lite"
[1] npm ERR! node v5.4.1
[1] npm ERR! npm  v3.3.12
[1] npm ERR!
[1]  code ELIFECYCLE
[1] npm ERR!
[1]  angular2-tour-of-heroes@0.0.1 lite: `lite-server`
[1] npm ERR!
[1]  Exit status 1
[1] npm ERR!
[1]  
[1] npm ERR! Failed at the angular2-tour-of-heroes@0.0.1 lite script 'lite-server'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
[1] npm ERR! not with npm itself.
[1] npm
[1]  ERR! Tell the author that this fails on your system:
[1] npm ERR!     lite-server
[1] npm ERR! You can get their info via:
[1] npm ERR!     npm owner ls angular2-tour-of-heroes
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /home/user/projects/samples/angular2-tour-of-heroes-master/npm-debug.log
[1] npm run lite exited with code 1
[0] 9:39:50 AM - Compilation complete. Watching for file changes.

**Comment by DirectX** [comment]
Seems like found the problem - that's due to lack of watchers in OS:
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

Worked to me:
    echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

**Comment by surajadh** [comment]
I also saw this error. Simply doing npm i and npm start seems to be not working for windows 10.

**Comment by jarnail104** [comment]
I am starting work on Angular2. I installed NodeJS following this url: http://blog.teamtreehouse.com/install-node-js-npm-windows

```
Everything work according to mention in above article and I am able run TEST too. I can check version of npm and node by 'node -v' and 'npm -v' commands but when i start 'npm start' its giving below error. And localhost:3001 is not working. I tried localhost:8080, localhost:3000 too but nothing working.
```

Below is issue on command

$ npm start
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8
npm ERR! path D:\myangular\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\myangular\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! D:\myangular\npm-debug.log
