### ISSUE TITLE
AOT broken

### ISSUE THREAD

**Issue by ihorskyi** [johnpapa/angular2-tour-of-heroes#92]
```
$ npm run start-aot


> angular2-tour-of-heroes@0.1.0 start-aot /private/tmp/angular2-tour-of-heroes
> npm run aot && npm run rollup && gulp copy-aot && npm run lite


> angular2-tour-of-heroes@0.1.0 aot /private/tmp/angular2-tour-of-heroes
> ngc -p tsconfig-aot.json

/private/tmp/angular2-tour-of-heroes/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10
exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl;
                                                  ^

TypeError: Cannot read property 'AssetUrl' of undefined
    at Object.<anonymous> (/private/tmp/angular2-tour-of-heroes/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10:51)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/angular2-tour-of-heroes/node_modules/@angular/compiler-cli/src/reflector_host.js:13:33)
    at Module._compile (module.js:570:32)
```

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
