### ISSUE TITLE
Issues AoT compilation

### ISSUE THREAD

**Issue by mloayzagahona** [johnpapa/angular2-tour-of-heroes#93]
Hey.

I'm getting this error when I ran this

`````` js
npm run start-aot
``

```js
npm info it worked if it ends with ok
npm verb cli [ '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node',
npm verb cli   '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm',
npm verb cli   'run',
npm verb cli   'start-aot' ]
npm info using npm@3.8.6
npm info using node@v5.12.0
npm verb run-script [ 'prestart-aot', 'start-aot', 'poststart-aot' ]
npm info lifecycle angular2-tour-of-heroes@0.1.0~prestart-aot: angular2-tour-of-heroes@0.1.0
npm info lifecycle angular2-tour-of-heroes@0.1.0~start-aot: angular2-tour-of-heroes@0.1.0

> angular2-tour-of-heroes@0.1.0 start-aot /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
> npm run aot && npm run rollup && gulp copy-aot && npm run lite

npm info it worked if it ends with ok
npm verb cli [ '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node',
npm verb cli   '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm',
npm verb cli   'run',
npm verb cli   'aot' ]
npm info using npm@3.8.6
npm info using node@v5.12.0
npm verb run-script [ 'preaot', 'aot', 'postaot' ]
npm info lifecycle angular2-tour-of-heroes@0.1.0~preaot: angular2-tour-of-heroes@0.1.0
npm info lifecycle angular2-tour-of-heroes@0.1.0~aot: angular2-tour-of-heroes@0.1.0

> angular2-tour-of-heroes@0.1.0 aot /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
> ngc -p tsconfig-aot.json

Error: Error File '/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/typings/index.d.ts' not found.
    at Object.check (/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Object.main (/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/@angular/tsc-wrapped/src/main.js:26:15)
    at Object.<anonymous> (/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/@angular/compiler-cli/src/main.js:14:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
Compilation failed

npm verb lifecycle angular2-tour-of-heroes@0.1.0~aot: unsafe-perm in lifecycle true
npm verb lifecycle angular2-tour-of-heroes@0.1.0~aot: PATH: /Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/.bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/.bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0@global/bin:/Users/nzw118/.rvm/rubies/ruby-2.3.0/bin:/Users/nzw118/perl5/bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/development/upf/apache-maven-3.1.1/bin:/Users/nzw118/bin:/Users/nzw118/Applications/mongodb-osx-x86_64-3.2.5/bin:/development/android-sdk-macosx/platform-tools:/development/android-sdk-macosx/tools:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Applications/MacVim.app/Contents/MacOS/:/Users/nzw118/.rvm/bin
npm verb lifecycle angular2-tour-of-heroes@0.1.0~aot: CWD: /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
npm info lifecycle angular2-tour-of-heroes@0.1.0~aot: Failed to exec aot script
npm verb stack Error: angular2-tour-of-heroes@0.1.0 aot: `ngc -p tsconfig-aot.json`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at EventEmitter.emit (events.js:185:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:850:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid angular2-tour-of-heroes@0.1.0
npm verb cwd /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node" "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm" "run" "aot"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 aot: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 aot script 'ngc -p tsconfig-aot.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p tsconfig-aot.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-tour-of-heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/npm-debug.log

npm verb lifecycle angular2-tour-of-heroes@0.1.0~start-aot: unsafe-perm in lifecycle true
npm verb lifecycle angular2-tour-of-heroes@0.1.0~start-aot: PATH: /Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/.bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0@global/bin:/Users/nzw118/.rvm/rubies/ruby-2.3.0/bin:/Users/nzw118/perl5/bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/development/upf/apache-maven-3.1.1/bin:/Users/nzw118/bin:/Users/nzw118/Applications/mongodb-osx-x86_64-3.2.5/bin:/development/android-sdk-macosx/platform-tools:/development/android-sdk-macosx/tools:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Applications/MacVim.app/Contents/MacOS/:/Users/nzw118/.rvm/bin
npm verb lifecycle angular2-tour-of-heroes@0.1.0~start-aot: CWD: /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
npm info lifecycle angular2-tour-of-heroes@0.1.0~start-aot: Failed to exec start-aot script
npm verb stack Error: angular2-tour-of-heroes@0.1.0 start-aot: `npm run aot && npm run rollup && gulp copy-aot && npm run lite`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at EventEmitter.emit (events.js:185:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:850:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid angular2-tour-of-heroes@0.1.0
npm verb cwd /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node" "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm" "run" "start-aot"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 start-aot: `npm run aot && npm run rollup && gulp copy-aot && npm run lite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 start-aot script 'npm run aot && npm run rollup && gulp copy-aot && npm run lite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run aot && npm run rollup && gulp copy-aot && npm run lite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-tour-of-heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
``````

The process is looking for this file: 

./angular2-tour-of-heroes/typings/index.d.ts

**Comment by mloayzagahona** [comment]
Here the npm-debug.log file

``` js
0 info it worked if it ends with ok
1 verbose cli [ '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node',
1 verbose cli   '/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-aot' ]
2 info using npm@3.8.6
3 info using node@v5.12.0
4 verbose run-script [ 'prestart-aot', 'start-aot', 'poststart-aot' ]
5 info lifecycle angular2-tour-of-heroes@0.1.0~prestart-aot: angular2-tour-of-heroes@0.1.0
6 silly lifecycle angular2-tour-of-heroes@0.1.0~prestart-aot: no script for prestart-aot, continuing
7 info lifecycle angular2-tour-of-heroes@0.1.0~start-aot: angular2-tour-of-heroes@0.1.0
8 verbose lifecycle angular2-tour-of-heroes@0.1.0~start-aot: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-tour-of-heroes@0.1.0~start-aot: PATH: /Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/nzw118/WorkspaceNg/angular2-tour-of-heroes/node_modules/.bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0/bin:/Users/nzw118/.rvm/gems/ruby-2.3.0@global/bin:/Users/nzw118/.rvm/rubies/ruby-2.3.0/bin:/Users/nzw118/perl5/bin:/Users/nzw118/.nvm/versions/node/v5.12.0/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/development/upf/apache-maven-3.1.1/bin:/Users/nzw118/bin:/Users/nzw118/Applications/mongodb-osx-x86_64-3.2.5/bin:/development/android-sdk-macosx/platform-tools:/development/android-sdk-macosx/tools:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Applications/MacVim.app/Contents/MacOS/:/Users/nzw118/.rvm/bin
10 verbose lifecycle angular2-tour-of-heroes@0.1.0~start-aot: CWD: /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
11 silly lifecycle angular2-tour-of-heroes@0.1.0~start-aot: Args: [ '-c',
11 silly lifecycle   'npm run aot && npm run rollup && gulp copy-aot && npm run lite' ]
12 silly lifecycle angular2-tour-of-heroes@0.1.0~start-aot: Returned: code: 1  signal: null
13 info lifecycle angular2-tour-of-heroes@0.1.0~start-aot: Failed to exec start-aot script
14 verbose stack Error: angular2-tour-of-heroes@0.1.0 start-aot: `npm run aot && npm run rollup && gulp copy-aot && npm run lite`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/nzw118/.nvm/versions/node/v5.12.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-tour-of-heroes@0.1.0
16 verbose cwd /Users/nzw118/WorkspaceNg/angular2-tour-of-heroes
17 error Darwin 15.6.0
18 error argv "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/node" "/Users/nzw118/.nvm/versions/node/v5.12.0/bin/npm" "run" "start-aot"
19 error node v5.12.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error angular2-tour-of-heroes@0.1.0 start-aot: `npm run aot && npm run rollup && gulp copy-aot && npm run lite`
22 error Exit status 1
23 error Failed at the angular2-tour-of-heroes@0.1.0 start-aot script 'npm run aot && npm run rollup && gulp copy-aot && npm run lite'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-tour-of-heroes package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run aot && npm run rollup && gulp copy-aot && npm run lite
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-tour-of-heroes
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-tour-of-heroes
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by mloayzagahona** [comment]
I think, you should include this link in your README.md doc  

https://angular.io/docs/ts/latest/cookbook/aot-compiler.html

In order to get a better knowledge about what you are trying to do it.

Just I've started with AngularJs 2. By the way, I'd like your video

Build Angular 2 apps with TypeScript and Visual Studio Code - https://www.youtube.com/watch?v=zoCLEwFUpqg&index=13&list=PLRcubY9Hxz6f6CqorQkt5F1xuZZx0vP44

Thanks

**Comment by dannypule** [comment]
I'm running into the same ..../typings/index.d.ts' not found issue. Anyone here have any leads on fixing this?

**Comment by domenichelfenstein** [comment]
+1, having the same problem

**Comment by anil1712** [comment]
I am getting below error while running AoT.

<code>
 ngc -p tsconfig-aot.json

Error: Unexpected value 'NgSemanticModule' imported by the module 'AppModule'
    at F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:13996:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:13981:46)
    at F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12801:47
    at Array.forEach (native)
    at analyzeModules (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12800:17)
    at OfflineCompiler.analyzeModules (F:\project_web\node_modules\@angular\compiler\bundles\compiler.umd.js:12826:18)
</code>

## Please help me to out of it.

I did follows below steps.
1. First I have installed
   `npm install ng-semantic --save`
2. Updated system.config.ts
   <code>
   map: {..
   ...
   ..
   'ng-semantic': 'npm:ng-semantic'
   ..
   }
   packages: {
   ....
   ..
   'ng-semantic': { main: './ng-semantic.js', defaultExtension: 'js' }
   }
   </code>
3. Imported modules in app.modules.ts

`import { NgSemanticModule } from "ng-semantic";`
`imports: [
....
NgSemanticModule
....
]`

Then run the AoT command

`npm run start-aot`

Then I got the above errors.
Please let me know if am I doing something wrong.

**Comment by anil1712** [comment]
Did anyone get any solution for above issue?

**Comment by brona90** [comment]
+1 bump

**Comment by scottescue** [comment]
The original problem @mloayzagahona reported showed up when 'typings' was removed.  It appears tsconfig-aot.json just needs to be updated to work with the changes.

**Comment by minuz** [comment]
Just downloaded the project and was having the same issue.
Can easily be fixed by updating the tsconfig as pointed out by @scottescue 

include the following on `tsconfig.json` and `tsconfig-aot.json`, compilerOptions
`
   "typeRoots": [
      "node_modules/@types"
    ]
`

Then you should be able to run `npm run start-aot`

**Comment by altaf933** [comment]
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "types": [],
    **"typeRoots": [ "node_modules/@types" ]**
  }

I have added this tsconfig.json and tsconfig-aot.json file . But not resolved yet

**Comment by tsureshpandi** [comment]
Install this for use ngc command.
npm install @angular/compiler-cli typescript@next @angular/platform-server @angular/compiler

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
